#!/bin/bash


. /home/vermes/ccc3/usr/setenv/unix/bashrcx

cd /home/vermes/amoeba-web

echo $USER
pwd


rm  -f log-webapp*

export PATH=`pwd`/program:$PATH

# teszteleshez  : export AMOEBA_CONTINUOUS_PLAY=1
# hatastalan    : export AMOEBA_CELLSIZE=32
# lehetseges    : export AMOEBA_TABLESIZE=14

# export AMOEBA_TABLESIZE=16
 export AMOEBA_BLINK=1
 export AMOEBA_POWER=auto.8+
# export AMOEBA_POWER_BLACK=3+
# export AMOEBA_POWER_WHITE=2

webapp.exe   | tee log-amoeba


